name: Make docs

env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '1.4.2'

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  docs:
    name: Build docs & publish them
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository default branch
        uses: actions/checkout@v3

      - name: Check out repository default branch
        run: git fetch origin gh-pages

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local  # the path depends on the OS
          key: poetry-0  # increment to reset cache

      - name: Install and configure Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --only docs

      - name: Build
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "dontemailthis@users.noreply.github.com"
          poetry run mike deploy --update-aliases develop --push
